/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LocaleRouteImport } from './routes/$locale'
import { Route as LocaleIndexRouteImport } from './routes/$locale.index'
import { Route as LocaleAuthModeRouteImport } from './routes/$locale.auth.$mode'
import { Route as LocaleDashboardAdminRouteImport } from './routes/$locale.dashboard.admin'
import { Route as LocaleDashboardUserRouteImport } from './routes/$locale.dashboard.user'
import { Route as LocaleDashboardAdminIndexRouteImport } from './routes/$locale.dashboard.admin.index'
import { Route as LocaleDashboardUserIndexRouteImport } from './routes/$locale.dashboard.user.index'
import { Route as LocaleDashboardUserQrGeneratorRouteImport } from './routes/$locale.dashboard.user.qr-generator'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LocaleRoute = LocaleRouteImport.update({
  id: '/$locale',
  path: '/$locale',
  getParentRoute: () => rootRouteImport,
} as any)
const LocaleIndexRoute = LocaleIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LocaleRoute,
} as any)
const LocaleAuthModeRoute = LocaleAuthModeRouteImport.update({
  id: '/auth/$mode',
  path: '/auth/$mode',
  getParentRoute: () => LocaleRoute,
} as any)
const LocaleDashboardAdminRoute = LocaleDashboardAdminRouteImport.update({
  id: '/dashboard/admin',
  path: '/dashboard/admin',
  getParentRoute: () => LocaleRoute,
} as any)
const LocaleDashboardUserRoute = LocaleDashboardUserRouteImport.update({
  id: '/dashboard/user',
  path: '/dashboard/user',
  getParentRoute: () => LocaleRoute,
} as any)
const LocaleDashboardAdminIndexRoute =
  LocaleDashboardAdminIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => LocaleDashboardAdminRoute,
  } as any)
const LocaleDashboardUserIndexRoute =
  LocaleDashboardUserIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => LocaleDashboardUserRoute,
  } as any)
const LocaleDashboardUserQrGeneratorRoute =
  LocaleDashboardUserQrGeneratorRouteImport.update({
    id: '/qr-generator',
    path: '/qr-generator',
    getParentRoute: () => LocaleDashboardUserRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$locale': typeof LocaleRouteWithChildren
  '/$locale/': typeof LocaleIndexRoute
  '/$locale/auth/$mode': typeof LocaleAuthModeRoute
  '/$locale/dashboard/admin': typeof LocaleDashboardAdminRouteWithChildren
  '/$locale/dashboard/user': typeof LocaleDashboardUserRouteWithChildren
  '/$locale/dashboard/user/qr-generator': typeof LocaleDashboardUserQrGeneratorRoute
  '/$locale/dashboard/admin/': typeof LocaleDashboardAdminIndexRoute
  '/$locale/dashboard/user/': typeof LocaleDashboardUserIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$locale': typeof LocaleIndexRoute
  '/$locale/auth/$mode': typeof LocaleAuthModeRoute
  '/$locale/dashboard/user/qr-generator': typeof LocaleDashboardUserQrGeneratorRoute
  '/$locale/dashboard/admin': typeof LocaleDashboardAdminIndexRoute
  '/$locale/dashboard/user': typeof LocaleDashboardUserIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$locale': typeof LocaleRouteWithChildren
  '/$locale/': typeof LocaleIndexRoute
  '/$locale/auth/$mode': typeof LocaleAuthModeRoute
  '/$locale/dashboard/admin': typeof LocaleDashboardAdminRouteWithChildren
  '/$locale/dashboard/user': typeof LocaleDashboardUserRouteWithChildren
  '/$locale/dashboard/user/qr-generator': typeof LocaleDashboardUserQrGeneratorRoute
  '/$locale/dashboard/admin/': typeof LocaleDashboardAdminIndexRoute
  '/$locale/dashboard/user/': typeof LocaleDashboardUserIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$locale'
    | '/$locale/'
    | '/$locale/auth/$mode'
    | '/$locale/dashboard/admin'
    | '/$locale/dashboard/user'
    | '/$locale/dashboard/user/qr-generator'
    | '/$locale/dashboard/admin/'
    | '/$locale/dashboard/user/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$locale'
    | '/$locale/auth/$mode'
    | '/$locale/dashboard/user/qr-generator'
    | '/$locale/dashboard/admin'
    | '/$locale/dashboard/user'
  id:
    | '__root__'
    | '/'
    | '/$locale'
    | '/$locale/'
    | '/$locale/auth/$mode'
    | '/$locale/dashboard/admin'
    | '/$locale/dashboard/user'
    | '/$locale/dashboard/user/qr-generator'
    | '/$locale/dashboard/admin/'
    | '/$locale/dashboard/user/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LocaleRoute: typeof LocaleRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$locale': {
      id: '/$locale'
      path: '/$locale'
      fullPath: '/$locale'
      preLoaderRoute: typeof LocaleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$locale/': {
      id: '/$locale/'
      path: '/'
      fullPath: '/$locale/'
      preLoaderRoute: typeof LocaleIndexRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/auth/$mode': {
      id: '/$locale/auth/$mode'
      path: '/auth/$mode'
      fullPath: '/$locale/auth/$mode'
      preLoaderRoute: typeof LocaleAuthModeRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/dashboard/admin': {
      id: '/$locale/dashboard/admin'
      path: '/dashboard/admin'
      fullPath: '/$locale/dashboard/admin'
      preLoaderRoute: typeof LocaleDashboardAdminRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/dashboard/user': {
      id: '/$locale/dashboard/user'
      path: '/dashboard/user'
      fullPath: '/$locale/dashboard/user'
      preLoaderRoute: typeof LocaleDashboardUserRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/dashboard/admin/': {
      id: '/$locale/dashboard/admin/'
      path: '/'
      fullPath: '/$locale/dashboard/admin/'
      preLoaderRoute: typeof LocaleDashboardAdminIndexRouteImport
      parentRoute: typeof LocaleDashboardAdminRoute
    }
    '/$locale/dashboard/user/': {
      id: '/$locale/dashboard/user/'
      path: '/'
      fullPath: '/$locale/dashboard/user/'
      preLoaderRoute: typeof LocaleDashboardUserIndexRouteImport
      parentRoute: typeof LocaleDashboardUserRoute
    }
    '/$locale/dashboard/user/qr-generator': {
      id: '/$locale/dashboard/user/qr-generator'
      path: '/qr-generator'
      fullPath: '/$locale/dashboard/user/qr-generator'
      preLoaderRoute: typeof LocaleDashboardUserQrGeneratorRouteImport
      parentRoute: typeof LocaleDashboardUserRoute
    }
  }
}

interface LocaleDashboardAdminRouteChildren {
  LocaleDashboardAdminIndexRoute: typeof LocaleDashboardAdminIndexRoute
}

const LocaleDashboardAdminRouteChildren: LocaleDashboardAdminRouteChildren = {
  LocaleDashboardAdminIndexRoute: LocaleDashboardAdminIndexRoute,
}

const LocaleDashboardAdminRouteWithChildren =
  LocaleDashboardAdminRoute._addFileChildren(LocaleDashboardAdminRouteChildren)

interface LocaleDashboardUserRouteChildren {
  LocaleDashboardUserQrGeneratorRoute: typeof LocaleDashboardUserQrGeneratorRoute
  LocaleDashboardUserIndexRoute: typeof LocaleDashboardUserIndexRoute
}

const LocaleDashboardUserRouteChildren: LocaleDashboardUserRouteChildren = {
  LocaleDashboardUserQrGeneratorRoute: LocaleDashboardUserQrGeneratorRoute,
  LocaleDashboardUserIndexRoute: LocaleDashboardUserIndexRoute,
}

const LocaleDashboardUserRouteWithChildren =
  LocaleDashboardUserRoute._addFileChildren(LocaleDashboardUserRouteChildren)

interface LocaleRouteChildren {
  LocaleIndexRoute: typeof LocaleIndexRoute
  LocaleAuthModeRoute: typeof LocaleAuthModeRoute
  LocaleDashboardAdminRoute: typeof LocaleDashboardAdminRouteWithChildren
  LocaleDashboardUserRoute: typeof LocaleDashboardUserRouteWithChildren
}

const LocaleRouteChildren: LocaleRouteChildren = {
  LocaleIndexRoute: LocaleIndexRoute,
  LocaleAuthModeRoute: LocaleAuthModeRoute,
  LocaleDashboardAdminRoute: LocaleDashboardAdminRouteWithChildren,
  LocaleDashboardUserRoute: LocaleDashboardUserRouteWithChildren,
}

const LocaleRouteWithChildren =
  LocaleRoute._addFileChildren(LocaleRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LocaleRoute: LocaleRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
